### ISSUE TITLE
Segfault in src/CBot/CBotVar/CBotVarValue.h, IncludeStyleRule

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot-lint#13]
Sorry that it's from release build but building takes so long that I'm too lazy to rebuild it :stuck_out_tongue:

```
Processing /home/krzys_h/.CLion2016.2/system/cmake/generated/colobot-14dd6097/14dd6097/Debug/fake_header_sources/src/CBot/CBotVar/CBotVarValue.cpp [fake header mode]

Program received signal SIGSEGV, Segmentation fault.
0x00000000004b8140 in IncludeStyleRule::run(clang::ast_matchers::MatchFinder::MatchResult const&) ()
(gdb) bt
#0  0x00000000004b8140 in IncludeStyleRule::run(clang::ast_matchers::MatchFinder::MatchResult const&) ()
#1  0x000000000054bbe9 in clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::MatchVisitor::visitMatch(clang::ast_matchers::BoundNodes const&) ()
#2  0x000000000055d2c3 in clang::ast_matchers::internal::BoundNodesTreeBuilder::visitMatches(clang::ast_matchers::internal::BoundNodesTreeBuilder::Visitor*) ()
#3  0x000000000054cdb2 in clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::matchWithFilter(clang::ast_type_traits::DynTypedNode const&) ()
#4  0x000000000055701d in clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::TraverseDecl(clang::Decl*) ()
#5  0x000000000055b4ed in clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseClassTemplateDecl(clang::ClassTemplateDecl*) ()
#6  0x00000000005561f4 in clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseDecl(clang::Decl*) ()
#7  0x0000000000557028 in clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::TraverseDecl(clang::Decl*) ()
#8  0x00000000005578b7 in clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseDeclContextHelper(clang::DeclContext*) ()
#9  0x000000000055642e in clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseDecl(clang::Decl*) ()
#10 0x0000000000557028 in clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::TraverseDecl(clang::Decl*) ()
#11 0x00000000005578b7 in clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseDeclContextHelper(clang::DeclContext*) ()
#12 0x0000000000555cd1 in clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseDecl(clang::Decl*) ()
#13 0x0000000000557028 in clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::TraverseDecl(clang::Decl*) ()
#14 0x00000000005574a5 in clang::ast_matchers::MatchFinder::matchAST(clang::ASTContext&) ()
#15 0x00000000005a5558 in clang::MultiplexConsumer::HandleTranslationUnit(clang::ASTContext&) ()
#16 0x0000000000639b7a in clang::ParseAST(clang::Sema&, bool, bool) ()
#17 0x000000000058a8e6 in clang::FrontendAction::Execute() ()
#18 0x0000000000565a39 in clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) ()
#19 0x0000000000519bc7 in clang::tooling::FrontendActionFactory::runInvocation(clang::CompilerInvocation*, clang::FileManager*, clang::DiagnosticConsumer*) ()
#20 0x0000000000518ad2 in clang::tooling::ToolInvocation::run() ()
#21 0x0000000000519468 in clang::tooling::ClangTool::run(clang::tooling::ToolAction*) ()
#22 0x00000000004700d7 in main ()
```

**Comment by piotrdz** [comment]
Fixed.
